package com.meshlit.core.inference.net

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonIgnoreUnknownKeys

/**
 * Phase 2 — the handshake frame the client sends as the *first*
 * packet on a freshly opened [RawTcpActivationChannel]. After the
 * FirstStage replies with a [PipelineStartAck], subsequent frames
 * on the same socket are [ActivationPacket]s — one per generated
 * token.
 *
 * Wire shape (v1):
 *  - `protocolVersion` is bumped on breaking changes. Today it's
 *    `1`. Unknown fields are tolerated via
 *    `Json { ignoreUnknownKeys = true }`.
 *  - `manifestSha256` lets the receiving FirstStage verify it's
 *    hosting the same shard manifest as the caller before it
 *    commits to allocating KV cache. Mismatch → reply with
 *    `ok = false, reason = "manifest_sha_mismatch"`.
 *  - `topologyId` is a stable hash of the assignment table. The
 *    FirstStage uses it as a key into its pipeline cache so a
 *    second request for the same topology reuses the open channel
 *    + KV context instead of rebuilding from scratch.
 *  - `cancelToken` is a UUID generated by the caller. The
 *    FirstStage includes it in any error frames so the caller can
 *    correlate a failure to a specific request when multiple
 *    pipelines are in flight.
 *
 * Phase 3 — async token batching knobs:
 *  - `batchSize` is the desired in-flight batch size. The
 *    FirstStage will flush a [MicroBatch] once it accumulates
 *    `batchSize` requests OR `batchTimeoutMs` elapses, whichever
 *    comes first. `batchSize = 1` = Phase 2 semantics (no
 *    batching).
 *  - `batchTimeoutMs` is the flush deadline. Even if the queue
 *    isn't full, the orchestrator will flush after this many ms so
 *    the caller doesn't wait indefinitely for slow trickle traffic.
 *
 * The packet intentionally does NOT carry the full prompt or
 * sampler config in the body — the prompt is too large to repeat
 * per-token, and sampler config is currently fixed per-model. A
 * future protocol bump can add `samplerOverrides: SamplerHints` if
 * the user ever needs per-request temperature / top_p overrides.
 */
@Serializable
@JsonIgnoreUnknownKeys
data class PipelineStartPacket(
    val protocolVersion: Int = PROTOCOL_VERSION,
    val prompt: String,
    val manifestSha256: String,
    val topologyId: String,
    val cancelToken: String? = null,
    /** Phase 3 — desired batch size. `1` = Phase 2 (no batching). */
    val batchSize: Int = DEFAULT_BATCH_SIZE,
    /** Phase 3 — flush deadline when the queue isn't full. */
    val batchTimeoutMs: Long = DEFAULT_BATCH_TIMEOUT_MS,
) {
    companion object {
        /** Current wire-protocol version. Bumped on breaking changes. */
        const val PROTOCOL_VERSION: Int = 1

        /** Phase 3 default — single-prompt per channel (Phase 2). */
        const val DEFAULT_BATCH_SIZE: Int = 1

        /** Phase 3 default — flush within 50 ms even if queue isn't
         *  full, so trickle traffic doesn't stall. */
        const val DEFAULT_BATCH_TIMEOUT_MS: Long = 50L

        /** Phase 3 upper bound on `batchSize`. A single activation
         *  packet is ~4 KB of hidden state + ~64 KB of KV cache
         *  slice; capping batch size at 16 keeps a MicroBatch under
         *  1 MB, well within the 4 MB transport cap. */
        const val MAX_BATCH_SIZE: Int = 16
    }
}

/**
 * Phase 2 — the FirstStage's reply to a [PipelineStartPacket]. Sent
 * as the second frame on the activation channel. If `ok = false`
 * the client MUST close the channel; no further frames will arrive.
 *
 * Failure reasons:
 *  - `protocol_mismatch` — client sent a `protocolVersion` the
 *    FirstStage doesn't understand. Future-proofing: today only v1
 *    is supported; a Phase 2.5 protocol would set this when the
 *    client sends v2.
 *  - `manifest_sha_mismatch` — the manifest sha on the wire doesn't
 *    match the loaded shard. Catches the "client planned against
 *    the wrong manifest" bug.
 *  - `topology_id_unknown` — the topology hash isn't in the cache
 *    and the FirstStage can't rebuild it (manifest not loaded yet).
 *  - `kv_cache_full` — no room to allocate a new KV slot. Caller
 *    should retry on a different FirstStage.
 *  - `busy` — the FirstStage is already running another pipeline;
 *    caller should retry on a different FirstStage.
 *  - `batch_size_unsupported` — Phase 2 client sent `batchSize > 1`
 *    to a Phase 2 receiver; the ack echoes `resolvedBatchSize = 1`
 *    so the client falls back to Phase 2 semantics transparently.
 */
@Serializable
@JsonIgnoreUnknownKeys
data class PipelineStartAck(
    val ok: Boolean,
    val reason: String? = null,
    /** Resolved embedding dim. When `ok = true`, the client can
     *  size its outbound [ActivationPacket.hiddenState] buffer
     *  from this. When `ok = false`, the field is null. */
    val embeddingDim: Int? = null,
    /** Phase 3 — the resolved batch size after negotiation. The
     *  FirstStage may downgrade the caller (e.g. `MAX_BATCH_SIZE`
     *  exceeded → echoes `1`). The client uses this to size its
     *  [MicroBatch] envelopes going forward. */
    val resolvedBatchSize: Int = 1,
    /** Phase 3 — the resolved flush deadline in ms. Same
     *  downgrade semantics as `resolvedBatchSize`. */
    val resolvedBatchTimeoutMs: Long = PipelineStartPacket.DEFAULT_BATCH_TIMEOUT_MS,
)
